#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
eval "$(starship init zsh)"

export EDITOR=vi
eval "$(direnv hook zsh)"

export PATH=$PATH:/Users/ahayashi/go/bin

alias k='kubectl'
alias kg='kubectl get'
alias kgpo='kubectl get pods'
alias kgsvc='kubectl get services'
alias kgep='kubectl get endpoinds'
alias kga='kubectl get all'
alias kaf='kubectl apply -f'
alias kdf='kubectl delete -f'
alias kc='kubectl config'

export PATH=/usr/local/Cellar/curl/7.84.0/bin/:$PATH
export PATH=~/.nodebrew/current/bin:$PATH

